Console.WriteLine("введите a");
double a = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("введите b");
double b = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("введите c");
double c = Convert.ToDouble(Console.ReadLine());
double d = (a+b+c)/2;
Console.WriteLine( d );
double e = 2 * (a + c) - 3 * b;
Console.WriteLine(e);
